; Keep this language-name contract aligned with active 7Launcher installers.
; English stays first and is the fallback for an unmatched Windows locale.
Name: English;    MessagesFile: "compiler:Default.isl"
Name: Russian;    MessagesFile: "compiler:Languages\Russian.isl"
Name: French;     MessagesFile: "compiler:Languages\French.isl"
Name: Finnish;    MessagesFile: "compiler:Languages\Finnish.isl"
Name: Italian;    MessagesFile: "compiler:Languages\Italian.isl"
Name: German;     MessagesFile: "compiler:Languages\German.isl"
Name: Spanish;    MessagesFile: "compiler:Languages\Spanish.isl"
Name: Portuguese; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: Brazilian;  MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: Polish;     MessagesFile: "compiler:Languages\Polish.isl"
Name: Czech;      MessagesFile: "compiler:Languages\Czech.isl"
Name: Ukrainian;  MessagesFile: "compiler:Languages\Ukrainian.isl"
Name: Hungarian;  MessagesFile: "compiler:Languages\Hungarian.isl"
Name: Turkish;    MessagesFile: "compiler:Languages\Turkish.isl"
Name: Greek;      MessagesFile: "compiler:Languages\Greek.isl"
Name: Swedish;    MessagesFile: "compiler:Languages\Swedish.isl"
Name: Dutch;      MessagesFile: "compiler:Languages\Dutch.isl"
Name: sChinese;   MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: tChinese;   MessagesFile: "compiler:Languages\ChineseTraditional.isl"
Name: Japanese;   MessagesFile: "compiler:Languages\Japanese.isl"
Name: Korean;     MessagesFile: "compiler:Languages\Korean.isl"
Name: Romanian;   MessagesFile: "compiler:Languages\Romanian.isl"
Name: Bulgarian;  MessagesFile: "compiler:Languages\Bulgarian.isl"
Name: Danish;     MessagesFile: "compiler:Languages\Danish.isl"
Name: Norwegian;  MessagesFile: "compiler:Languages\Norwegian.isl"
Name: Thai;       MessagesFile: "compiler:Languages\Thai.isl"
